name: '🌐🤝 Networking'
description: 'Anything networking related regarding the project; e.g.: Connecting with other clubs/individuals/sponsors, planning events etc.'
title: '[Networking] '
labels: 'Networking


body:
- type: markdown
  attributes:
    value: "To expedite issue processing, please search open and closed issues before submitting a new one. Please read our Rules of Conduct at this repository's `.github/CODE_OF_CONDUCT.md`"
- type: markdown
  attributes:
    value: "# 🌐🤝 Networking"
- type: input
  attributes:
    label: Source Type
    description: Where the this issue/request originates from. E.g. a backlog ticket, QMS-Ticket (PIT) or Customer Feedback, Ideation Workshop Meeting, etc.
    placeholder: "e.g. 'Backlog'"
  validations:
    required: false
- type: input
  attributes:
    label: Source Link
    description: E.g. a link to the backlog ticket, customer support request, meeting notes etc.
    placeholder: "E.g. '#xyz' or 'https//...'"
  validations:
    required: false
- type: textarea
  attributes:
    label: Objective
    description: Provide a clear and concise description of the task at hand.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Information
    description: Include any additional information or context that might be helpful for reviewers or developers.
  validations:
    required: false
- type: markdown
  attributes:
    value: "_The following sections have to be filled by the person who is responsible for solving the bug._"
- type: textarea
  attributes:
    label: Execution
    description: (TO BE FILLED BY ASSIGNEE)
    placeholder: Provide a brief summary of the final decision and, if applicable, of the final solution and its outcome.
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution Path
    description: (TO BE FILLED BY ASSIGNEE)
    placeholder: If the task is more envolved than writing one email or equivalent, the solution path should be outlined. Use the `add tasklist` feature for easy planning.
  validations:
    required: false
